name: Generate metrics

on:
  schedule:
    - cron: "27 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: metrics
  cancel-in-progress: false

jobs:
  metrics:
    name: Generate cards
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 45
    steps:
      - name: Base overview
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ github.token }}
          user: ${{ github.repository_owner }}
          filename: metrics.base.svg
          base: header, activity, community, repositories, metadata
          base_indepth: "yes"
          repositories: 300
          repositories_affiliations: owner, collaborator, organization_member
          output_action: commit
          output_condition: data-changed
          optimize: css, xml, svg

      - name: Languages
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ github.token }}
          user: ${{ github.repository_owner }}
          filename: metrics.languages.svg
          base: header
          plugin_languages: "yes"
          plugin_languages_limit: 15
          plugin_languages_details: "yes"
          repositories: 200
          output_action: commit
          output_condition: data-changed
          optimize: css, xml, svg

      - name: Contributors
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ github.token }}
          user: ${{ github.repository_owner }}
          filename: metrics.contributors.svg
          base: header
          plugin_contributors: "yes"
          plugin_contributors_contributions: "yes"
          output_action: commit
          output_condition: data-changed
          optimize: css, xml, svg

      - name: Followup
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ github.token }}
          user: ${{ github.repository_owner }}
          filename: metrics.followup.svg
          base: header
          plugin_followup: "yes"
          plugin_followup_archived: "yes"
          output_action: commit
          output_condition: data-changed
          optimize: css, xml, svg

      - name: Stargazers
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ github.token }}
          user: ${{ github.repository_owner }}
          filename: metrics.stargazers.svg
          base: ""
          plugin_stargazers: "yes"
          plugin_stargazers_charts: type:heatmap
          plugin_stargazers_days: 30
          output_action: commit
          output_condition: data-changed
          optimize: css, xml, svg
